language: go

matrix:
  include:
    - os: linux
      go: "1.13.x"
    - os: linux
      go: "1.12.x"
    - os: osx
      go: "1.13.x"
    - os: osx
      go: "1.12.x"
    - os: windows
      go: "1.13.x"
    - os: windows
      go: "1.12.x"

env:
  - GO111MODULE=off

before_install:
  - go get -v -u github.com/dvyukov/go-fuzz/...
  - go get -v -u golang.org/x/tools/cmd/goimports
  - go get -v -u ./...

script:
  - go test ./fuzz ./randparam ./genfuzzfuncs
  - go test -short .
  - go test ./...
